name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Switch to Ubuntu, which has Docker pre-installed
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image with timestamp
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        shell: bash

      - name: Push Docker image
        run: docker push my-image-name:$(date +%s)
